version: "3.8"
services:
  postgres_ylab:
    container_name: postgres_ylab
    image: postgres:15.1-alpine
    env_file:
      - .env-non-dev
    environment:
      PGUSER: "postgres"
    expose:
      - 543
    ports:
      - 5433:5433
    networks:
      - ylab_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "postgres", "-d", "postgres"]
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 80s


  fastapi_ylab:
    container_name: fastapi_ylab
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env-non-dev
    entrypoint: sh -c "alembic upgrade head && cd src && uvicorn main:app --host 0.0.0.0 --port 8000"
    networks:
      - ylab_network
    ports:
      - 8000:8000
    depends_on:
      postgres_ylab:
        condition: service_healthy


networks:
  ylab_network:
    name: ylab_network
